### ISSUE TITLE
31mERROR

### ISSUE THREAD

**Issue by forp3tessake** [tsarbuig/LimitSwap#24]
I set up everything and when I run the bot I get:
2022-01-20 22:28:07.244592 ←[31mERROR. Please go to /log folder and open your logs: you will find more details.←[0m
2022-01-20 22:28:07.244592 Restarting LimitSwap

Log file:
INFO: 2022-01-20 22:28:00,254 YOUR BOT IS CURRENTLY RUNNING VERSION  4.2.1.2
INFO: 2022-01-20 22:28:00,988 Checking Latest Release Version on Github, Please Make Sure You are Staying Updated =  v4.2.1.2

ERROR: 2022-01-20 22:28:07,244 could not convert string to float: ''
Traceback (most recent call last):
  File "LimitSwap.py", line 4746, in run
  File "LimitSwap.py", line 723, in load_tokens_file
  File "LimitSwap.py", line 2010, in build_extended_base_configuration
ValueError: could not convert string to float: ''
INFO: 2022-01-20 22:28:07,244 ERROR. Please go to /log folder and open your logs: you will find more details.
ERROR: 2022-01-20 22:28:07,244 local variable 'token' referenced before assignment
Traceback (most recent call last):
  File "LimitSwap.py", line 4746, in run
  File "LimitSwap.py", line 723, in load_tokens_file
  File "LimitSwap.py", line 2010, in build_extended_base_configuration
ValueError: could not convert string to float: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LimitSwap.py", line 5226, in runLoop
  File "LimitSwap.py", line 5211, in run
UnboundLocalError: local variable 'token' referenced before assignment
ERROR: 2022-01-20 22:28:07,244 local variable 'token' referenced before assignment
Traceback (most recent call last):
  File "LimitSwap.py", line 4746, in run
  File "LimitSwap.py", line 723, in load_tokens_file
  File "LimitSwap.py", line 2010, in build_extended_base_configuration
ValueError: could not convert string to float: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LimitSwap.py", line 5226, in runLoop
  File "LimitSwap.py", line 5211, in run
UnboundLocalError: local variable 'token' referenced before assignment
ERROR: 2022-01-20 22:28:19,519 could not convert string to float: ''
Traceback (most recent call last):
  File "LimitSwap.py", line 4748, in run
  File "LimitSwap.py", line 910, in reload_tokens_file
  File "LimitSwap.py", line 2010, in build_extended_base_configuration
ValueError: could not convert string to float: ''
INFO: 2022-01-20 22:28:19,523 ERROR. Please go to /log folder and open your logs: you will find more details.
ERROR: 2022-01-20 22:28:19,523 local variable 'token' referenced before assignment
Traceback (most recent call last):
  File "LimitSwap.py", line 4748, in run
  File "LimitSwap.py", line 910, in reload_tokens_file
  File "LimitSwap.py", line 2010, in build_extended_base_configuration
ValueError: could not convert string to float: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LimitSwap.py", line 5226, in runLoop
  File "LimitSwap.py", line 5211, in run
UnboundLocalError: local variable 'token' referenced before assignment
ERROR: 2022-01-20 22:28:19,526 local variable 'token' referenced before assignment
Traceback (most recent call last):
  File "LimitSwap.py", line 4748, in run
  File "LimitSwap.py", line 910, in reload_tokens_file
  File "LimitSwap.py", line 2010, in build_extended_base_configuration
ValueError: could not convert string to float: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LimitSwap.py", line 5226, in runLoop
  File "LimitSwap.py", line 5211, in run
UnboundLocalError: local variable 'token' referenced before assignment

This is my tokens.json setup:
[
  {
    "ENABLED": "true",

    "SYMBOL": "flappy floki",
    "ADDRESS": "0xe477bb2F425C6184243e40174Fe276f281B1C8fB",
    "KIND_OF_SWAP": "base", // enter "base" to use BUYAMOUNTINBASE , and "tokens" to use BUYAMOUNTINTOKENS
    "BUYAMOUNTINBASE": "0.01",
    "BUYAMOUNTINTOKEN": "",
    "MAX_BASE_AMOUNT_PER_EXACT_TOKENS_TRANSACTION": "0.01", // used with KIND_OF_SWAP = tokens

    "BUYPRICEINBASE":  "0",
    "SELLPRICEINBASE": "999999999", // You can now put amount in % in this field
    "STOPLOSSPRICEINBASE": "", // You can now put amount in % in this field
    "SLIPPAGE": "49",

    "MOONBAG": "0", // Bot will keep this amount in your wallet after SELL order
    "MAXTOKENS": "1", // Bot will stop if your balance > MAXTOKENS
    "MAX_SUCCESS_TRANSACTIONS_IN_A_ROW": "2",
    "MAX_FAILED_TRANSACTIONS_IN_A_ROW": "2",

    "RUGDOC_CHECK": "false",
    "BUYAFTER_XXX_SECONDS": "0", // if you want the bot to wait XXX seconds before if makes the BUY Tx
    "WAIT_FOR_OPEN_TRADE": "false", // check Wiki, this is very useful
    "MULTIPLEBUYS": "false", // use this if you want bot to make multiple buys at the same time
    "BUYCOUNT": "",
    "ALWAYS_CHECK_BALANCE": "false", // use this if you want bot to check your token balance between each price check

    "MINIMUM_LIQUIDITY_IN_DOLLARS": "10000",
    "WATCH_STABLES_PAIRS": "true", // use this if you want bot to check all Stable Liquidity pairs

    "LIQUIDITYINNATIVETOKEN": "false",
    "USECUSTOMBASEPAIR": "false",
    "BASESYMBOL": "",
    "BASEADDRESS": "",

    "SELLAMOUNTINTOKENS": "0",
    "HASFEES": "true",
    "GAS": "50", // Team recommend you to use BOOST here
    "MAX_GAS": "", // Put here the maximum of GAS you want to pay if you use BOOST. If GAS > MAX_GAS Tx won't be made
    "BOOSTPERCENT": "30",
    "GASLIMIT": "2000000", // Team recommend you to use 1000000 here
    "GASPRIORITY_FOR_ETH_ONLY": "1.5"
  }
]

**Comment by tsarbuig** [comment]
https://t.me/LimitSwap/103769
