### ISSUE TITLE
problem when you use WATCH_STABLES_PAIRS with BUY_THE_DIP

### ISSUE THREAD

**Issue by tsarbuig** [tsarbuig/LimitSwap#48]
https://t.me/LimitSwap/109996

TypeError: can't multiply sequence by non-int of type 'float'
can't multiply sequence by non-int of type 'float'
Traceback (most recent call last):
  File "C:\Users\Louie\Desktop\Crypto\LimitSwap\LimitSwap-4.2.4.1\LimitSwap-4.2.4.1\LimitSwap.py", line 5728, in runLoop
    run()
  File "C:\Users\Louie\Desktop\Crypto\LimitSwap\LimitSwap-4.2.4.1\LimitSwap-4.2.4.1\LimitSwap.py", line 5148, in run
    tokens = load_tokens_file(command_line_args.tokens, True)
  File "C:\Users\Louie\Desktop\Crypto\LimitSwap\LimitSwap-4.2.4.1\LimitSwap-4.2.4.1\LimitSwap.py", line 746, in load_tokens_file
    for new_token_dict in build_extended_base_configuration(token):
  File "C:\Users\Louie\Desktop\Crypto\LimitSwap\LimitSwap-4.2.4.1\LimitSwap-4.2.4.1\LimitSwap.py", line 2214, in build_extended_base_configuration
    "BUYPRICEINBASE": token_dict['BUYPRICEINBASE'] * settings['_STABLE_BASES'][stable_token]['multiplier'],
TypeError: can't multiply sequence by non-int of type 'float'

**Comment by tsarbuig** [comment]
solved
