### ISSUE TITLE
when preapprove is set to yes, LimitSwap tries to approve a disabled token from another chain

### ISSUE THREAD

**Issue by vaidab** [tsarbuig/LimitSwap#56]
'RITE'
Traceback (most recent call last):
  File "LimitSwap.py", line 5830, in runLoop
    run()
  File "LimitSwap.py", line 5224, in run
    tokens = reload_tokens_file(command_line_args.tokens, True)
  File "LimitSwap.py", line 956, in reload_tokens_file
    '_LIQUIDITY_READY': _TOKENS_saved[token['SYMBOL']]['_LIQUIDITY_READY'],
KeyError: 'RITE'
Could not transact with/call contract function, is contract deployed correctly and chain synced?
Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.8/site-packages/web3/contract.py", line 1515, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "/home/xxx/.local/lib/python3.8/site-packages/eth_abi/codec.py", line 181, in decode_abi
    return decoder(stream)
  File "/home/xxx/.local/lib/python3.8/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/home/xxx/.local/lib/python3.8/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/home/xxx/.local/lib/python3.8/site-packages/eth_abi/decoding.py", line 173, in decode
    yield decoder(stream)
  File "/home/xxx/.local/lib/python3.8/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/home/xxx/.local/lib/python3.8/site-packages/eth_abi/decoding.py", line 198, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/home/xxx/.local/lib/python3.8/site-packages/eth_abi/decoding.py", line 305, in read_data_from_stream
    raise InsufficientDataBytes(
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "LimitSwap.py", line 5830, in runLoop
    run()
  File "LimitSwap.py", line 5294, in run
    token['_CONTRACT_DECIMALS'] = int(decimals(token['ADDRESS']))
  File "LimitSwap.py", line 2405, in decimals
    decimals = balanceContract.functions.decimals().call()
  File "/home/xxx/.local/lib/python3.8/site-packages/web3/contract.py", line 959, in call
    return call_contract_function(
  File "/home/xxx/.local/lib/python3.8/site-packages/web3/contract.py", line 1532, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?

**Comment by tsarbuig** [comment]
honestly I won't have time to solve this bro

The best way to use my bots on several blockchains are : 

1/ How I personally do 
I created several tokens.json and settings.json files, named for instance : 
- tokensBSC.json
- tokensAVAX.json
- tokensFTM.json
- etc.

And when I launch the bot, I use parameters like : 
`python LimitSwap.py -s settingsBSC.json -t tokensBSC.json`


2/ More professional 
you can use the Makefile, it works amazingly well
