### ISSUE TITLE
Intermittent error 32603 when leaving the bot to run over a time

### ISSUE THREAD

**Issue by vaidab** [tsarbuig/LimitSwap#61]
I get 3 consecutive errors (before of that log shows normal behavior):

{'code': -32603, 'message': 'empty resp'}
Traceback (most recent call last):
  File "LimitSwap.py", line 5830, in runLoop
    run()
  File "LimitSwap.py", line 5467, in run
    token['_QUOTE'] = check_precise_price(token['_IN_TOKEN'], token['_OUT_TOKEN'], token['_WETH_DECIMALS'], token['_CONTRACT_DECIMALS'], token['_BASE_DECIMALS'])
  File "LimitSwap.py", line 3283, in check_precise_price
    reserves = pair_contract.functions.getReserves().call()
  File "/home/X/.local/lib/python3.8/site-packages/web3/contract.py", line 959, in call
    return call_contract_function(
  File "/home/X/.local/lib/python3.8/site-packages/web3/contract.py", line 1503, in call_contract_function
    return_data = web3.eth.call(
  File "/home/X/.local/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/X/.local/lib/python3.8/site-packages/web3/manager.py", line 187, in request_blocking
    return self.formatted_response(response,
  File "/home/X/.local/lib/python3.8/site-packages/web3/manager.py", line 168, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32603, 'message': 'empty resp'}

**Comment by tsarbuig** [comment]
https://github.com/tsarbuig/LimitSwap/commit/d34e2c9e93e584d724599f40ce81012aee000ac2

this should help, tell me if it's better after updating with this code
